[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "beamng-blackboard"
version = "0.1.0"
description = "A lightweighted BlackBoard-like IPC implemented using BeamNG.tech as shared memory to synchronize remote driving agents with a central scenario executor"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beamngpy>=1.31",
]

[tool.setuptools]
packages = ["beamng_blackboard "]
package-dir = { beamng_blackboard  = "." }
